import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Sandra Barron',
  description: 'Generated by create next app',
};

const RootLayout: React.FC = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="custom-cursor">
          {children}
        </div>
        <Navbar />
      </body>
    </html>
  );
};

export default RootLayout;
